import SettingsIcon from "@components/icons/SettingsIcon";
import CodeBlock from "@components/ui/CodeBlock";
import CollapsibleSection from "@components/ui/CollapsibleSection";

const ServiceWorkerSection = () => {
  return (
    <>
      <div className="space-y-6">
        <div className="flex items-center space-x-3 mb-6">
          <SettingsIcon className="text-orange-400" width={32} height={32} />
          <h2 className="text-3xl font-bold text-white">Service Worker</h2>
        </div>

        <div className="bg-linear-to-r from-orange-900 to-red-900 p-6 rounded-lg border border-orange-500">
          <p className="text-gray-200">
            The service worker is automatically generated by next-pwa. However,
            you can customize caching strategies for better control.
          </p>
        </div>

        <CollapsibleSection title="Caching Strategies" id="caching-strategies">
          <div className="space-y-4">
            <div className="bg-blue-900 bg-opacity-30 border border-blue-500 rounded-lg p-4">
              <h4 className="font-semibold text-blue-400 mb-2">NetworkFirst</h4>
              <p className="text-gray-300 text-sm">
                Tries network first, falls back to cache if offline. Best for
                dynamic content.
              </p>
              <CodeBlock
                id="network-first"
                code={`{
       urlPattern: /^https?.*/,
       handler: 'NetworkFirst',
       options: {
         cacheName: 'dynamic-cache',
         expiration: {
           maxEntries: 50,
           maxAgeSeconds: 24 * 60 * 60, // 24 hours
         },
       },
     }`}
              />
            </div>

            <div className="bg-purple-900 bg-opacity-30 border border-purple-500 rounded-lg p-4">
              <h4 className="font-semibold text-purple-400 mb-2">CacheFirst</h4>
              <p className="text-gray-300 text-sm">
                Tries cache first, falls back to network. Best for static
                assets.
              </p>
              <CodeBlock
                id="cache-first"
                code={`{
       urlPattern: /\\.(?:png|jpg|jpeg|svg|gif|webp)$/,
       handler: 'CacheFirst',
       options: {
         cacheName: 'image-cache',
         expiration: {
           maxEntries: 100,
           maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
         },
       },
     }`}
              />
            </div>

            <div className="bg-green-900 bg-opacity-30 border border-green-500 rounded-lg p-4">
              <h4 className="font-semibold text-green-400 mb-2">
                StaleWhileRevalidate
              </h4>
              <p className="text-gray-300 text-sm">
                Serves cached version while fetching fresh data. Best balance of
                speed and freshness.
              </p>
              <CodeBlock
                id="stale-revalidate"
                code={`{
       urlPattern: /^https?:.*\\/api\\/.*/,
       handler: 'StaleWhileRevalidate',
       options: {
         cacheName: 'api-cache',
         expiration: {
           maxEntries: 32,
           maxAgeSeconds: 24 * 60 * 60, // 24 hours
         },
       },
     }`}
              />
            </div>
          </div>
        </CollapsibleSection>

        <CollapsibleSection title="Custom Service Worker" id="custom-sw">
          <p className="text-gray-300 mb-3">
            For advanced use cases, create{" "}
            <code className="bg-gray-900 px-2 py-1 rounded">public/sw.js</code>:
          </p>
          <CodeBlock
            id="custom-sw-code"
            code={`self.addEventListener('install', (event) => {
       console.log('Service Worker installing.');
       self.skipWaiting();
     });
     
     self.addEventListener('activate', (event) => {
       console.log('Service Worker activating.');
     });
     
     self.addEventListener('fetch', (event) => {
       // Custom fetch handling
       event.respondWith(
         caches.match(event.request).then((response) => {
           return response || fetch(event.request);
         })
       );
     });`}
          />
        </CollapsibleSection>
      </div>
    </>
  );
};

export default ServiceWorkerSection;
